server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Necesario para que react-router maneje las rutas en el cliente
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Healthcheck simple para el ALB / liveness probe de k8s
    location /healthz {
        access_log off;
        return 200 "ok\n";
    }
}
